name: CI
on:
    push:
      branches:
        - main
      tags:
        - 'v*'
    pull_request:

env:
  PYTHON_BUILD_VERSION: '3.14'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Install python
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --frozen

      - name: Check formatting
        run: make check-format

      - name: Check linting
        run: make check-fix

      - name: Run tests
        run: make test

      - name: Build package
        run: uv build

      - name: Upload artifacts
        if: matrix.python-version == env.PYTHON_BUILD_VERSION
        uses: actions/upload-artifact@v7
        with:
          name: python-package-distributions
          path: dist/
